### ISSUE TITLE
Plugin cordova?

### ISSUE THREAD

**Issue by moreirawebmaster** [DimatiBart/Web-Bluetooth-miBand-Demo#1]
Can I use the commands on the mobile (android) specifically phonegap or cordova?

**Comment by elliolir** [comment]
Since WebView on android use chromium it might get work. But in this case it would depend on android version (since webbluetooth api was added in android chrome 56). IMO for now would be better to use cordova plugin such as BluetoothSerial, cordova-ble or cordova-plugin-bluetoothle.
